### ISSUE TITLE
write build tests for react-app using travis ci

### ISSUE THREAD

**Issue by 98sean98** [rcltech/owl#12]
**Todo:**
- write a stage for testing if the react-app could be built without errors

**Potential issues:**
- learning curve of travis ci

**Possible solutions:**
- read https://docs.travis-ci.com/

**Additional notes (optional):**
- make use of `npm run build` script

**Comment by 98sean98** [comment]
@sidb28 let me know if you want to sit down and work on this issue together. I'll guide you through.

**Comment by sidb28** [comment]
I'll work on it ASAP

**Comment by welvin21** [comment]
Thanks Siddhant !

**Comment by welvin21** [comment]
Thanks! @sidb28
