### ISSUE TITLE
Fix 401 unauthorized post request status

### ISSUE THREAD

**Issue by welvin21** [rcltech/owl#22]
I was able to make post requests from react-app to the server which also sends relevant booking data to mongoDB. 

However, every time axios.post(url,data) is executed, I get this message on the console. I am not sure if this problem has to do with the client or server. Should we ignore this? Since they won't be visible by users.

<img width="572" alt="Screenshot 2019-09-27 at 3 59 39 PM" src="https://user-images.githubusercontent.com/47080921/65752954-7d6d9180-e140-11e9-8b16-61861e60d4f0.png">

**Comment by 98sean98** [comment]
I'm sorry. I made **breaking changes**. What we should achieve for now is React will send a `jwt` signed token containing the payload of the form:
```
const booking = {
    userId: process.env.DUMMY_USER_ID,
    room: '305',
    start: new Date(2019, 9, 20, 8),
    end: new Date(2019, 9, 20, 9)
  };
```
such that `DUMMY_USER_ID=dummy`. jwt signs the payload using its default algorithm and `API_KEY` (the one I sent to @welvin21 ). React should send `{ token }` using axios.

The following middleware will run every time a booking is created / read / updated / deleted.
```
const authUser = async (req, res, next) => {
  // temporary jwt signature to verify payload
  const token = req.body.token;
  jwt.verify(token, key, (error, payload) => {
    if (error || dummyUserId !== payload.userId)
      return handleError(
        res,
        error ? error : 'Invalid user',
        'Failed to auth user',
        401
      );
    req.body = payload;
  });
  next();
};
```

**This behavior has been tested and deployed to Heroku**

**Comment by welvin21** [comment]
I see, that's why it worked last night but not this morning. I will close this issue then, as we will not face  it once react is able to send the token.
