### ISSUE TITLE
Unsynchronized data between ChooseDate and ChooseTime pages.

### ISSUE THREAD

**Issue by welvin21** [rcltech/owl#90]
![issue](https://user-images.githubusercontent.com/47080921/72788707-539b2600-3c6d-11ea-86c2-7fab459318ea.gif)

Whenever we select different months or years from the current date, there is an unsynchronized data issue between the two sections. User has to specifically click the corresponding date at least one.

**Comment by 98sean98** [comment]
observed this behaviour since a while ago, thanks for pointing out
